baseURL = "https://blog.frank30941.nctu.me/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-nix"

[params]
  Name = "Teng-Wei, Hsieh"
  HeaderUsername = "Frank Hsieh"
  HeaderHostname = "frank30941"
  About = "I like to learn new technologys, and I am a lazy man, yes it is me."
  ProfilePicture = "https://i.imgur.com/WDy60W6.jpg?1"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"